version: "3"

services:
  voltage:
    build:
      dockerfile: Dockerfile
    entrypoint: ["npm", "run", "dev"]
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./node_modules:/app/node_modules
    ports:
      - "5173:5173"
