version: "3"

services:

  voltage-client:
    build:
      dockerfile: Dockerfile
    image: voltage-client-dev:latest
    container_name: voltage-client
    env_file:
      - env/.env.dev
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
      - ./node_modules:/app/node_modules
      - ./vite.config.js:/app/vite.config.js
    ports:
      - "5173:5173"
