version: "3"

services:

  voltage-client:
    build:
      dockerfile: Dockerfile
    image: voltage-client-dev:latest
    container_name: voltage-client
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./node_modules:/app/node_modules
    ports:
      - "5173:5173"
