FROM node:18-alpine as build

WORKDIR /app
COPY package.json ./

RUN npm install
COPY . ./app

RUN npm run test && npm run build


FROM nginx:1.24-alpine as serve

ENV NODE_ENV production
# Copy built assets from `builder` image
COPY --from=builder /app/build /usr/share/nginx/html
# Add your nginx.conf
COPY /app/deploy_tools/nginx.conf /etc/nginx/conf.d/default.conf
