export const baseUrl = "http://localhost:5000/api/v1";
export const changePasswordUrl = baseUrl + "/change_password/";
export const confirmUrl = baseUrl + "/confirm/"
export const stationsUrl = baseUrl + "/stations/";
export const lastReportsUrl = baseUrl + "/lastreports";
export const reportCountUrl = baseUrl + "/reportcount/";
export const tokensUrl = baseUrl + "/tokens/";
export const registerUrl = baseUrl + "/new_user/";
export const reconfirmUrl = baseUrl + "/confirm";
export const resetUrl = baseUrl + "/reset";
export const resetPasswordUrl = baseUrl + "/reset/"
