const stations = {
    'Acatlan': 'Acatlán',
    'AguaCaliente': 'Agua Caliente',
    'Almoyola': 'Almoyola',
    'Ayutla': 'Ayutla',
    'Cacalutla': 'Cacalutla',
    'CaletaCampos': 'Caleta Campos',
    'Caracol': 'Caracol',
    'CdAltamirano': 'Cd Altamirano',
    'CerrodeOro': 'Cerro de Oro',
    'Chazumba': 'Chazumba',
    'Cienequilla': 'Cienequilla',
    'CofadiaJuarez': 'Cofadia Juárez',
    'Colomilla': 'Colomilla',
    'Constitucion': 'Constitución',
    'CorralPiedra': 'Corral Piedra',
    'Cuajimoloyas': 'Cuajimoloyas',
    'ElCarrizo': 'El Carrizo',
    'ElCortes': 'El Cortés',
    'ElDuin': 'El Duin',
    'ElHerradero': 'El Herradero',
    'ElJardin': 'El Jardin',
    'ElPortezuelo': 'El Portezuelo',
    'ElVeinte': 'El Veinte',
    'ElVenado': 'El Venado',
    'Guixe': 'Guixe',
    'HuamelulaSP': 'Huamelula SP',
    'HuazolotitlanSM': 'Huazolotitlán SM',
    'Huehuetan': 'Huehuetán',
    'HumoChico': 'Humo Chico',
    'Infiernillo': 'Infiernillo',
    'Joluta': 'Joluta',
    'LaCentral': 'La Central',
    'LaPiedra': 'La Piedra',
    'LaPintada': 'La Pintada',
    'LaReforma': 'La Reforma',
    'LaVillita': 'La Villita',
    'LaVirgen': 'La Virgen',
    'Lachiquiri': 'Lachiquiri',
    'LasAdjuntas': 'Las Adjuntas',
    'LasGarzas': 'Las Garzas',
    'LasMesas': 'Las Mesas',
    'LasPenas': 'Las Peñas',
    'LasVigas': 'Las Vigas',
    'LlanoGrande': 'Llano Grande',
    'LlanosAmuzgos': 'Llanos Amuzgos',
    'MTacubaya': 'M Tacubaya',
    'Marquelia': 'Marquelia',
    'Maruata': 'Maruata',
    'MazatanSV': 'Mazatán SV',
    'Mezcala': 'Mezcala',
    'Mitlalcingo': 'Mitlalcingo',
    'MixtepecSP': 'Mixtepec SP',
    'Mixtequilla': 'Mixtequilla',
    'Morelos': 'Morelos',
    'OjodeAgua': 'Ojo de Agua',
    'Olinala': 'Olinalá',
    'PalmaSola': 'Palma Sola',
    'Pantla': 'Pantla',
    'Papanoa': 'Papanoa',
    'Penjamo': 'Pénjamo',
    'Petatlan': 'Petatlán',
    'PiedraGrande': 'Piedra Grande',
    'Pilcaya': 'Pilcaya',
    'Providencia': 'Providencia',
    'PtoBalsamo': 'Pto Bálsamo',
    'PuertoAngel': 'Puerto Angel',
    'Quetzalapa': 'Quetzalapa',
    'RivTonameca': 'Riv Tonameca',
    'SanGeronimo': 'San Gerónimo',
    'SanJeronimo': 'San Jerónimo',
    'SanMateo': 'San Mateo',
    'SanPedro': 'San Pedro',
    'SanTelmo': 'San Telmo',
    'SantaLucia': 'Santa Lucia',
    'SoladeVega': 'Sola de Vega',
    'Tamazulapam': 'Tamazulapam',
    'Tangolunda': 'Tangolunda',
    'Tecomatlan': 'Tecomatlán',
    'Tehuacan': 'Tehuacán',
    'Tehuitzingo': 'Tehuitzingo',
    'Temazcal': 'Temazcal',
    'Tenango': 'Tenango',
    'TeojomulcoSD': 'Teojomulco SD',
    'Tepeji': 'Tepeji',
    'Tequixtepec': 'Tequixtepec',
    'Tetitlan': 'Tetitlán',
    'Tlachichilco': 'Tlachichilco',
    'Tlacotepec': 'Tlacotepec',
    'Tonalapa': 'Tonalapa',
    'Troncones': 'Troncones',
    'Tututepec': 'Tututepec',
    'Vigastepec': 'Vigastepec',
    'VistaHermosa': 'Vista Hermosa',
    'Yucudaa': 'Yucudaa',
    'Zihuatanejo': 'Zihuatanejo'
};

export default stations;
